version: '3.8'

services:
  web:
    build: .
    container_name: lumio_web
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=lumio
      - DB_USER=root
      - DB_PASS=secret
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: lumio_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lumio
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
      # Exécute automatiquement database.sql au premier démarrage de la base de données
      - ./database/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
